"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$username$hostname$git_branch$git_commit$git_state$git_metrics$git_status$all$character"""
# format = """$directory$username$hostname$git_branch$git_commit$git_state$git_metrics$git_status$fill$all$character"""
add_newline = true
palette = 'custom'

[palettes.custom]
orange = "#fab387"

[character]
success_symbol = '[❯](bold orange)'
vimcmd_symbol = '[❮](bold orange)'

[directory]
style = "yellow"
home_symbol = "~"

[username]
show_always = true
format = '[\($user]($style)'
style_user = 'bold red'
style_root = 'bold green'

[hostname]
format = '[@$ssh_symbol$hostname\)]($style) '
ssh_only = false
style = 'bold red'

[fill]
symbol = ' '
