# Monitors
monitor=DP-2,highrr,0x0,1
monitor=HDMI-A-1,preferred,-2160x-1100,1,transform,3
monitor=DP-1,highrr,0x-1440,1

# Execs (Startup applications)
exec-once=gammastep -l 39.962:-82.996
exec-once=sleep 5; streamcontroller -b
exec-once=sleep 5; xrandr --output DP-2 --primary

# Launch and tile all apps via layout script
exec-once=sleep 3; /home/tony/.dotfiles/scripts/nighthawk-layout.sh

# Workspaces
workspace=name:1, monitor:DP-2, persistent:true, default:true
workspace=name:2, monitor:DP-2, persistent:true
workspace=name:3, monitor:DP-2, persistent:true
workspace=name:4, monitor:DP-2, persistent:true
workspace=name:right-monitor, monitor:HDMI-A-1, default:true, persistent:true
workspace=name:top-monitor, monitor:DP-1, default:true, persistent:true

# Notepad (special workspace)
# windowrule {
#   name = obsidian-notepad
#   match:class = ^(obsidian)$
#   float = on
#   size = 2580 2000
#   move = 50 50
#   workspace = special
#   opacity = 0.95
# }

windowrule {
  name = claude-notes
  match:title = ^(claude-notes)$
  float = on
  size = 1120 2000
  move = 2670 50
  workspace = special
  opacity = 0.95
}

# Startup workspace assignments (right monitor)
windowrule = workspace right-monitor silent, match:class ^(vesktop)$
windowrule = workspace right-monitor silent, match:class ^(FFPWA-01KBH7FDJN0SMRXM47M6HHR694)$
windowrule = workspace right-monitor silent, match:class ^(Element)$

# Move Google Meet to Vertical Monitor and Tile
windowrule {
  name = google-meet
  match:title = ^(Google Meet)
  tile = on
  monitor = HDMI-A-1
}

# Move Spotify to Top Monitor
windowrule = workspace top-monitor silent, match:title ^(Spotify)
windowrule = workspace top-monitor silent, match:class ^(spotify)$

# Waybar
exec-once=sleep 1; dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && uwsm app -- waybar

# NVIDIA
env = _JAVA_AWT_WM_NONREPARENTING=1
env = PROTON_ENABLE_NGX_UPDATER,1
env = NVD_BACKEND,direct
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1
env = WLR_USE_LIBINPUT,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
# env = WLR_DRM_NO_ATOMIC,1

# NOTE: THIS SHOULD NOT BE USED!
# env = GBM_BACKEND,nvidia-drm
env = WLR_DRM_DEVICES,/dev/dri/card0

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# testing
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = APPIMAGELAUNCHER_DISABLE,1
